### PR TITLE
Updates in Location Field and layout 

### PR DESCRIPTION
**Pull request by irinaz**
@sherakama 
Hi Shea, 
We had two reviews with Tori and Joy this week, here is "beta2" version.  I hope that it will build properly in JS right away and we could test it before review tomorrow. 

Thanks, Irina

### CODE REVIEW

**Comment by sherakama** [comment]
Hello Irina, this PR is going to the master branch. We have been working on the 7.x-1.x branch. I have created that pull request for you here: https://github.com/SU-SWS/stanford_fellowship/pull/3. 

It looks like there is a git merge conflict. I will have to find some time to resolve this before I can review the pull request.

**Comment by irinaz** [comment]
Shea,
My apologies - I am still struggling with git process.  I guess I did 
not merge some of your changes.

I will attempt to revert my changes, pull in  your changes, and the add 
mine.    Not sure when I can complete this, and I very much appreciate 
you training me on git operations.

Thanks, Irina

**Comment by sherakama** [comment]
@irinaz,

Don't fret about this. Conflicts happen. To resolve this issue I would merge the work from SU-SWS/stanford_fellowship's 7.x-1.x branch in to your branch then review the conflicts.

Here is a great article on how to resolve conflicts:
http://www.git-tower.com/learn/git/ebook/command-line/advanced-topics/merge-conflicts

**Comment by sherakama** [comment]
@irinaz,

Please close this PR as it is going to the wrong branch.

**Comment by sherakama** [comment]
@irinaz,

Please close this PR as it is going to the wrong branch.

**Comment by sherakama** [comment]
@irinaz,

Please close this PR as it is going to the wrong branch.

**Comment by sherakama** [comment]
Yay, thank you.

**Pull request closed without merging**
